### ISSUE TITLE
"Prefetch" feature

### ISSUE THREAD

**Issue by snellingio** [postlight/trimmings#15]
Might be best left to turbolinks, although there is no movement on them ever implementing this.

See: https://gist.github.com/hopsoft/ab500a3b584e2878c83137cb539abb32 && https://github.com/turbolinks/turbolinks/issues/313

I am seeing it as a `data-trimmings-prefetch="true"` or similar.

**Comment by johnholdun** [comment]
Yeah, I think implementing this in Trimmings would break cross-compatibility with Turbolinks, or add a lot of complexity (and explicit knowledge of the Turbolinks API) in order to not break it. Trimmings is, in general, more about facilitating the triggering of native DOM-related events, rather than extending or overloading them, so I don't think this fits the project.

I'd love to see that gist you links packaged up and provided as its own isolated script that kicks in when it detects that Turbolinks is installed, though–and then it would work just fine alongside Trimmings too!
